name: tool_base
description: Base for developing command line apps. Take from Flutter Tools.
version: 1.10.0
homepage: https://github.com/DrBu7cher/tool_base
publish_to: none

environment:
  # The pub client defaults to an <2.0.0 sdk constraint which we need to explicitly overwrite.
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  # To update these, use "flutter update-packages --force-upgrade".
  archive: ">=3.3.0"
  file: ">=6.1.0"
  intl: ">=0.17.0"
  platform: ">=3.1.0"
  process: ">=4.2.0"

dev_dependencies:
  file_testing: ^3.0.0
  mockito: ^5.4.0
  quiver: ^3.2.1
  test: ^1.24.1
